version: '3'

## NOTES:
# if you see ${SOME_VAR} in this file,
# these values are taken from .env file

#########################
#          DEV          #
#########################

services:

    nginx:
        image: nginx
        restart: "${RESTART_POLICIES}"
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - "$PWD:/home/docker"
            - "$PWD/.docker/dev/dev.conf:/etc/nginx/conf.d/default.conf:ro"
        networks:
            - "symfony"

    symfony:
        build:
            context: ./.docker/dev/
            args:
                - "DOCKER_USER=${DOCKER_USER}"
                - "DOCKER_USER_ID=${DOCKER_USER_ID}"
                - "GIT_USER_NAME=${GIT_USER_NAME}"
                - "GIT_USER_EMAIL=${GIT_USER_EMAIL}"
        image: symfony3_docker:dev
        restart: "${RESTART_POLICIES}"
        environment:
            - "XDEBUG_CONFIG=remote_host=${REMOTE_HOST}"
        volumes:
            - "$PWD:/home/docker"
            - "$PWD/.docker/dev/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
        working_dir: "/home/docker"
        user: "${DOCKER_USER}"
        networks:
            - "symfony"

    db:
        image: mysql:5.6
        restart: "${RESTART_POLICIES}"
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
          - "$PWD/.data/db:/var/lib/mysql:Z"
        networks:
            - "symfony"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: "${RESTART_POLICIES}"
        environment:
            - "PMA_HOST=db"
            - "PMA_USER=root"
            - "PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        ports:
            - "${PMA_PORT}:80"
        depends_on:
            - "db"
        networks:
            - "symfony"

    mailhog:
        image: mailhog/mailhog
        restart: "${RESTART_POLICIES}"
        ports:
            - "${MAILHOG_PORT}:8025"
            - "1025:1025"
        networks:
            - "symfony"

networks:
    symfony:
        driver: bridge
