version: '2'

## NOTES:
# if you see ${SOME_VAR} in this file,
# these values are taken from .env file

#########################
#         PROD          #
#########################

services:

    nginx:
        image: nginx
        restart: "${RESTART_POLICIES}"
        ports:
            - "${NGINX_PORT}:80"
        links:
            - "symfony:symfony"
        volumes:
            - ".:/home/docker"
            - "./app/Resources/docker/default.conf:/etc/nginx/conf.d/default.conf:ro"

    symfony:
        build:
            context: ./app/Resources/docker/
            args:
                - "DOCKER_USER=${DOCKER_USER}"
        restart: "${RESTART_POLICIES}"
        links:
            - "db:db"
        volumes:
            - ".:/home/docker"
            - "./app/Resources/docker/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
        working_dir: "/home/docker"
        user: "${DOCKER_USER}"

    db:
        image: mysql:5.7
        restart: "${RESTART_POLICIES}"
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
          - "./.data/db:/var/lib/mysql:Z"
