version: '2'

## NOTES:
# if you see ${SOME_VAR} in this file,
# these values are taken from .env file

#########################
#          DEV          #
#########################

services:
    nginx:
        image: nginx
        container_name: nginx
        restart: "${RESTART_POLICIES}"
        dns_search: "symfony.dev"
        ports:
            - "${NGINX_PORT}:80"
        links:
            - "symfony:symfony"
        volumes:
            - ".:/home/docker"
            - "./app/Resources/docker/default.conf:/etc/nginx/conf.d/default.conf:ro"

    symfony:
        build:
            context: ./app/Resources/docker/
            args:
                - "DOCKER_USER=${DOCKER_USER}"
        container_name: symfony
        restart: "${RESTART_POLICIES}"
        links:
            - "db:db"
            - "mailcatcher:mailcatcher"
        volumes:
            - ".:/home/docker"
            - "./app/Resources/docker/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
        working_dir: "/home/docker"
        user: "${DOCKER_USER}"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: myadmin
        restart: "${RESTART_POLICIES}"
        environment:
            - "PMA_HOST=db"
            - "PMA_USER=${MYSQL_USER}"
            - "PMA_PASSWORD=${MYSQL_PASSWORD}"
        ports:
            - "${PMA_PORT}:80"
        depends_on:
            - "db"

    db:
        image: mysql:5.7
        container_name: db
        restart: "${RESTART_POLICIES}"
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
          - "./.data/db:/var/lib/mysql"

    mailcatcher:
        image: yappabe/mailcatcher
        container_name: mailcatcher
        restart: "${RESTART_POLICIES}"
        ports:
            - "${MAILCATCHER_PORT}:1080"
            - "1025:1025"
